=== A24Moises/html/XML Documents/codeLanguage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="code">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="language" type="languageType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="languageType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="application" type="applicationType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="applicationType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== A24Moises/html/XML Documents/codeLanguage.xml
<?xml version="1.0" encoding="UTF-8"?>
<code xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="codeLanguage.xsd">
    <language>
        <name>Java</name>
        <description>Java is a high-level programming language developed by Sun Microsystems.</description>
        <type>Object-oriented</type>
        <aplication>
            <name>Web Applications</name>
            <name>Mobile Applications</name>
        </aplication>    
    </language>
    <language>
        <name>Python</name>
        <description>Python is a high-level programming language developed by Guido van Rossum.</description>
        <type>Object-oriented</type>
        <aplication>
            <name>Web Applications</name>
            <name>Mobile Applications</name>
        </aplication>
    </language>
    <language>
        <name>JavaScript</name>
        <description>JavaScript is a high-level programming language developed by Netscape.</description>
        <type>Object-oriented</type>
        <aplication>
            <name>Web Applications</name>
            <name>Mobile Applications</name>
        </aplication>
    </language>
</code>
