<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE computerShop [
    <!ELEMENT computerShop (products, costumer?, sale?)>
    <!ELEMENT products (product+)>
    <!ELEMENT product (title, manufacturer, model, price, currency, priceDiscount?, stock, recondicioned, vat, ean?)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT manufacturer (#PCDATA)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT currencyP (#PCDATA)>
    <!ELEMENT priceDiscount (#PCDATA)>
    <!ELEMENT stock (#PCDATA)>
    <!ELEMENT reconditioned (#PCDATA)>
    <!ELEMENT vat (#PCDATA)>
    <!ELEMENT ean (#PCDATA)>
    <!ATTLIST identifierP idP IDREF #REQUIRED>
    <!ATTLIST currencyP money IDREF #IMPLIED>
    <!ATTLIST priceDiscount percent IDREF #REQUIRED>
    <!ATTLIST vat status IDREF #REQUIRED>
    <!ATTLIST ean codBar IDREF #REQUIRED>

    <!ELEMENT costumer (identifierC, idCard, firstName, surNames, telephoneNumber, postalAddress, creationDate)*>
    <!ELEMENT identifierC (#PCDATA)>
    <!ELEMENT idCard (#PCDATA)> 
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT surName (#PCDATA)>
    <!ELEMENT telephoneNumber (#PCDATA)>
    <!ELEMENT postalAddress (#PCDATA)>
    <!ELEMENT creationDate (#PCDATA)>
    <!ATTLIST identifierC idC IDREF #REQUIRED>
    <!ATTLIST creationDate dateC ID #REQUIRED>
    
    <!ELEMENT sale (dateSale, customer, productSold, productID, quantitySold, totalPrice, currency)*>
    <!ELEMENT dateSale (#PCDATA)>
    <!ELEMENT customer (#PCDATA)>
    <!ELEMENT productSold (#PCDATA)>
    <!ELEMENT productID (#PCDATA)>
    <!ELEMENT qualitySold (#PCDATA)>
    <!ELEMENT totalPrice (#PCDATA)>
    <!ELEMENT currencyS (#PCDATA)>
    <!ATTLIST dateSale dateS IDREF #REQUIRED>
    <!ATTLIST customer idC IDREF #IMPLIED>
    <!ATTLIST productID idP IDREF #IMPLIED>
]>

<computerShop>
    <products>
            <product idP="p1">
                <title></title>
                <manufacturer></manufacturer>
                <model></model>
                <price></price>
                <currencyP money="eur"></currencyP>
                <priceDiscount percent="percent0"/>
                <stock></stock>
                <reconditioned></reconditioned>
                <vat status="general"></vat>
                <ean codBar=""></ean> 
            </product>
            <product>
                <identifierP idP="p2"/>
                <title></title>
                <manufacturer></manufacturer>
                <model></model>
                <price></price>
                <currencyP money="usd"></currencyP>
                <priceDiscount percent="percent20"></priceDiscount>
                <stock></stock>
                <reconditioned></reconditioned>
                <vat status="reduced"></vat>
                <ean codBar=""></ean>
            </product>
            <product>
                <identifierP idP="p3"/>
                <title></title>
                <manufacturer></manufacturer>
                <model></model>
                <price></price>
                <currencyP money="eur"></currencyP>
                <priceDiscount percent="percent20"></priceDiscount>
                <stock></stock>
                <reconditioned></reconditioned>
                <vat status="super-reduced"></vat>
                <ean codBar=""></ean>
            </product>
        </products>
        <costumer>
            <identifierC idC=""></identifierC>
            <idCard>12345678</idCard>
            <firstName>Juan</firstName>
            <surName>Perez</surName>
            <telephoneNumber></telephoneNumber>
            <postalAddress></postalAddress>
            <creationDate dateC=""></creationDate>
        </costumer>
        <sale>
            <dateSale dateS=""></dateSale>
            <customer idC=""></customer>
            <productSold></productSold>
            <productID idP=""></productID>
            <quantitySold></quantitySold>
            <totalPrice></totalPrice>
            <currencyS></currencyS>
        </sale>
</computerShop>